name: ros2-simple-listener-cpp
version: '2.2.2'
summary: Snap with simple ROS 2 listener - devmode
description: |
  A simple ROS 2 listener which receives ROS 2 messages on topic 'ros2_simple_cpp'.

base: core22
grade: stable
confinement: devmode

parts:
  ros-app:
    plugin: dump
    source: install
    override-build: |
        snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-listener.sh : usr/bin/run-listener

  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz
    plugin: autotools

apps:
  listener:
    command: usr/bin/run-listener
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s
  bash:
    command: usr/local/bin/bash
    plugs:
      - ros-base
      - network
      - network-bind

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
 