# This is a basic workflow to help you get started with Actions

name: Mkdocs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  BuildSnaps:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        run: snap install snapcraft
      -
        run: |
          cd simple-listener-py
          ./build-snap-amd64.sh
          
